### PR TITLE
adding palemoon compatibility

### PR DESCRIPTION
**Pull request by intika**

### CODE REVIEW

**Comment by tumpio** [comment]
How does it work on Pale Moon? I haven't tried it myself. Is everything ok?

**Comment by intika** [comment]
everything is okay :) it work fine

**Comment by tumpio** [comment]
Great! Thanks.

**Comment by Lootyhoof** [comment]
Can confirm the core add-on works as expected. However, a few things:

- The `Invert tab backgrounds` option doesn't have any effect (as Pale Moon doesn't generally use `.tab-background`, but rather styles the whole `.tabbrowser-tab`); should just need a conditional to separate the two, I'd say, since the styling seems fine otherwise.
- In Pale Moon, the notification bar is already housed in `#browser-bottombox`, so this option is unnecessary.
- The menu bar isn't draggable.
- Pale Moon still uses `#addon-bar` as its status bar, and it looks like you explicitly ignore that (due to its odd use in Firefox I presume), so the status bar cannot be dragged (probably just needs a conditional as above?).

I should also note that AMO doesn't like Pale Moon too much, so while users can still it, the actual listing shows it (and will show it, once updated) as "incompatible" due to the higher Firefox `minVersion`; if this is a particular concern though Pale Moon does offer an add-ons site where autoupdates are provided for Pale Moon users. If this is of interest please see [here](http://developer.palemoon.org/Add-ons:Site) and let me know.

**Comment by tumpio** [comment]
Something to work on then :) Thanks for your report @Lootyhoof

**Comment by intika** [comment]
Hi tumpio... 
you should post your addon into the addon webpage
http://developer.palemoon.org/Add-ons:Site
have a look at it when you have the time ;)

**Pull request merged**
